#!/bin/bash

echo "🚀 GitHub Repository Setup"
echo "=========================="
echo ""
echo "1. Go to https://github.com and create a new repository"
echo "   - Name: portfolio-backend"
echo "   - Make it PUBLIC"
echo "   - Don't add README (we already have one)"
echo ""
echo "2. After creating the repository, copy the repository URL"
echo "   It should look like: https://github.com/YOUR_USERNAME/portfolio-backend.git"
echo ""
echo "3. Replace YOUR_USERNAME in the command below and run it:"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/portfolio-backend.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "4. Then deploy to Railway:"
echo "   - Go to https://railway.app"
echo "   - Sign up/Login with GitHub"
echo "   - Click 'New Project'"
echo "   - Select 'Deploy from GitHub repo'"
echo "   - Select your portfolio-backend repository"
echo ""
echo "5. Set environment variables in Railway dashboard"
echo ""
echo "6. Your app will be available at: https://your-app-name.railway.app/api"
echo ""
echo "Need help? Let me know your GitHub username and I'll help you set it up!" 